create table if not exists gb_post_tag(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL UNIQUE COMMENT '标签名',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='文章标签表';
